CREATE OR REPLACE PACKAGE      "RAJINI_PKG" IS
FUNCTION TO_NUMBER_RAJINI(V_IPCHAR VARCHAR2) RETURN NUMBER;
FUNCTION SYSDATE_TOMORROW RETURN DATE;
FUNCTION SYSDATE_SPELLED_OUT RETURN VARCHAR2;
PROCEDURE PUT_LINE_RAJINI(P_INPUT VARCHAR2);

END RAJINI_PKG;
/


CREATE OR REPLACE PACKAGE BODY RAJINI_PKG IS

FUNCTION TO_NUMBER_RAJINI(V_IPCHAR VARCHAR2) 
RETURN NUMBER IS
BEGIN
RETURN TO_NUMBER(V_IPCHAR);
EXCEPTION
WHEN OTHERS THEN
RETURN 
NULL;
END TO_NUMBER_RAJINI;

 FUNCTION SYSDATE_TOMORROW
RETURN DATE IS
BEGIN
RETURN SYSDATE+1;
END SYSDATE_TOMORROW;

FUNCTION SYSDATE_SPELLED_OUT
RETURN VARCHAR2 IS
BEGIN
RETURN TO_CHAR(SYSDATE,'DD - MONTH-YEAR HH24:MI:SS');

END SYSDATE_SPELLED_OUT;

PROCEDURE PUT_LINE_RAJINI(P_INPUT VARCHAR2)
IS
BEGIN
DBMS_OUTPUT.PUT_LINE(P_INPUT);
END PUT_LINE_RAJINI;


END RAJINI_PKG;
/
